### ISSUE TITLE
這個 mode 要是能真的在漢字和英文之間加上空格就好了

### ISSUE THREAD

**Issue by xieyuheng** [coldnew/pangu-spacing#12]
爲什麼要滿足於
只是顯示出來空格的效果
而不真的加空格呢

**Comment by xieyuheng** [comment]
哦 ~
我看到 (setq pangu-spacing-real-insert-separtor t) 了
太棒了
*^-^*

**Comment by xieyuheng** [comment]
(add-hook 'local-write-file-hooks 'pangu-spacing-modify-buffer)
因爲你把這個函數加到 local-write-file-hooks 裏了
所以每次空格只有在 C-x C-s 的時候才能真正添加到漢字與英文之間

是不是如果不這樣做的話
速度就慢的沒法接受 ?

**Comment by coldnew** [comment]
是怕影響到其他 mode 的功能，還有 `添加空白到漢字與英文之間` 是一個很危險的事情，所以讓使用者自己決定是否適合儲存。 (反正 emacs 特性就是我不爽我自己改 XD)

另外，目前已知啟用 `local-write-file-hooks` 會影響到 org-mode 部分功能，如 links (中英混雜連結)，請見 #5 , #10
