### ISSUE TITLE
PR #28 make some pangu-spacing function not work correctly

### ISSUE THREAD

**Issue by coldnew** [coldnew/pangu-spacing#29]
see #28

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/4723751/56412554-2f15b600-62b7-11e9-871c-16458e6d5a1a.png">

Here is the steps I took:
1. opened emacs with `emacs -q pangu-spacing.el`
2. `M-x eval-buffer`
3. `M-x switch-to-buffer` `*scratch*`
4. `M-x pangu-spacing-mode`
5. paste `跟alex解释 task 弹性的问题`

_Originally posted by @dsdshcym in https://github.com/coldnew/pangu-spacing/pull/28#issuecomment-484791270_

**Comment by yangsheng6810** [comment]
@coldnew Could you test if #30 fixes this? I also added some simple tests to make sure things work.

**Comment by coldnew** [comment]
@yangsheng6810 I think #30 worked, I'll merge it
