### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by zzjjzzgggg** [coldnew/pangu-spacing#33]
If one English character is between two Chinese characters, I get `中 1文`, which seems to be incorrect.
 
If two or more English characters are between two Chinese characters, I get `中 11 文`, which is correct.

Can anyone reproduce this bug? Thx!

**Comment by yangsheng6810** [comment]
Having the same problem. Could you check #34 ?

**Comment by zzjjzzgggg** [comment]
This fixed the bug. Thanks!
