### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by yuutayamada** [coldnew/pangu-spacing#9]
I think the `pangu-spacing-real-insert-separtor` should be `pangu-spacing-real-insert-separator`.
(separtor -> separator)
Am I right?

**Comment by coldnew** [comment]
Yes you're right, I didn't notice this typo until now ....
I'll think how to fix this (also need to prevent affect old users).

Thank you :)

**Comment by yuutayamada** [comment]
You are welcome!
